server {
    listen 80 default;
    server_name _;
    client_max_body_size 128M;
    root /var/www/html;
    index index.php index.html;
    location / { try_files $uri $uri/ /index.php?$args; }
    location ~ ^.+\.php {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
    }
    location ~ /\.ht { deny all; }
}
